# Generated by Django 2.1.7 on 2019-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("jedi_resourses", "0006_auto_20190524_1213")]

    operations = [
        migrations.RenameModel(old_name="Podowan", new_name="Padawan"),
        migrations.AlterModelOptions(
            name="padawan",
            options={"verbose_name": "Падаван", "verbose_name_plural": "Падаваны"},
        ),
    ]
